<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="azstorageexp" name="ChromeTest" tests="6" failures="1" timestamp="5 Mar 2020 14:56:51 GMT" time="42.766" errors="0">
  <testcase name="Login" time="2.467" classname="com.bookmyfurniture.testcases.LoginTest"/>
  <testcase name="Logout" time="16.993" classname="com.bookmyfurniture.testcases.LoginTest"/>
  <testcase name="LoginWithWrongPassword" time="1.823" classname="com.bookmyfurniture.testcases.LoginTest"/>
  <testcase name="registerFurniture" time="24.397" classname="com.bookmyfurniture.testcases.RegisterTest"/>
  <testcase name="faiTest" time="0.003" classname="com.bookmyfurniture.testcases.RegisterTest">
    <failure type="java.lang.AssertionError" message="This test fails">
      <![CDATA[java.lang.AssertionError: This test fails
	at com.bookmyfurniture.testcases.RegisterTest.faiTest(RegisterTest.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- faiTest -->
  <testcase name="LoginWithoutEmailId" time="7.655" classname="com.bookmyfurniture.testcases.LoginTest"/>
</testsuite> <!-- ChromeTest -->
